# Generated by Django 3.1.1 on 2022-04-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('seq', models.IntegerField(blank=True, db_column='Seq', primary_key=True, serialize=False)),
                ('symbol', models.TextField(blank=True, db_column='Symbol', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('url', models.TextField(blank=True, db_column='Url', null=True)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
